# Generated by Django 3.1.3 on 2020-11-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_auto_20201126_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='r_id',
            new_name='Родительский идентификатор',
        ),
    ]
