# Generated by Django 3.1.3 on 2020-11-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_auto_20201127_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='Родительский идентификатор',
        ),
        migrations.AddField(
            model_name='element',
            name='rod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='handbook.handbook', verbose_name='Родительский идентификатор'),
        ),
    ]
