# Generated by Django 3.1.3 on 2020-11-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0005_auto_20201127_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='rod',
            new_name='handbook',
        ),
    ]
